### ISSUE TITLE
chore: add renovate bot

### ISSUE THREAD

**Issue by codespearhead** [bgizdov/quarkus-multi-module-project-quickstart#2]
Add [Renovate Bot](https://github.com/marketplace/renovate) to the repository to keep the project dependencies updated, like in [this repository](https://github.com/appiepollo14/quarkus-realworld-api/commits/master/).

Once you add it to the repository, [a PR will be created like this one](https://github.com/codespearhead/quarkus-multi-module-project-quickstart/pull/1). You just have to accept it and call it a day.

**Comment by bgizdov** [comment]
Thanks for the suggestion, I think it is enabled now.
